# Generated by Django 3.1.4 on 2020-12-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Unpublish', 'Unpublish')], default='Unpublish', max_length=50, null=True),
        ),
    ]
