# Generated by Django 3.1.4 on 2020-12-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201219_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
