# Generated by Django 3.1.4 on 2020-12-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201219_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
