# Generated by Django 3.1.4 on 2020-12-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201221_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=500000000000000000000000000000000000, null=True, unique=True),
        ),
    ]
