# Generated by Django 3.1.4 on 2020-12-22 00:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201221_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article',
            field=tinymce.models.HTMLField(),
        ),
    ]
