# Generated by Django 3.1.4 on 2020-12-22 00:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201221_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
